import React from "react";

const areaData = [
    {"cityName": "Karachi", "areaName": "Abul Isphani Road"},
    {"cityName": "Karachi", "areaName": "Abdullah Haroon Road"},
    {"cityName": "Karachi", "areaName": "Abid Town"},
    {"cityName": "Karachi", "areaName": "Abu Zar Ghaffari"},
    {"cityName": "Karachi", "areaName": "Abul Hassan Isphani Road"},
    {"cityName": "Karachi", "areaName": "Agra Taj Colony"},
    {"cityName": "Karachi", "areaName": "Airport"},
    {"cityName": "Karachi", "areaName": "Akhtar Colony"},
    {"cityName": "Karachi", "areaName": "Allama Iqbal Colony"},
    {"cityName": "Karachi", "areaName": "Aligarh Colony"},
    {"cityName": "Karachi", "areaName": "Amil Colony"},
    {"cityName": "Karachi", "areaName": "Amir Khusro"},
    {"cityName": "Karachi", "areaName": "Ancholi"},
    {"cityName": "Karachi", "areaName": "Anda Mor Road"},
    {"cityName": "Karachi", "areaName": "Ayesha Nagar"},
    {"cityName": "Karachi", "areaName": "Askari i"},
    {"cityName": "Karachi", "areaName": "Askari ii"},
    {"cityName": "Karachi", "areaName": "Askari iii"},
    {"cityName": "Karachi", "areaName": "Askari iv"},
    {"cityName": "Karachi", "areaName": "Askari v"},
    {"cityName": "Karachi", "areaName": "Azizabad"},
    {"cityName": "Karachi", "areaName": "Azam Basti"},
    {"cityName": "Karachi", "areaName": "Bahadurabad"},
    {"cityName": "Karachi", "areaName": "Baloch Colony"},
    {"cityName": "Karachi", "areaName": "Bath Island"},
    {"cityName": "Karachi", "areaName": "Beaumont Road"},
    {"cityName": "Karachi", "areaName": "Bhittai Colony"},
    {"cityName": "Karachi", "areaName": "Bilal Colony"},
    {"cityName": "Karachi", "areaName": "Bangla Bazaar"},
    {"cityName": "Karachi", "areaName": "Bilal Town"},
    {"cityName": "Karachi", "areaName": "Bihar Muslim Society"},
    {"cityName": "Karachi", "areaName": "Bolton Market"},
    {"cityName": "Karachi", "areaName": "Britto Road"},
    {"cityName": "Karachi", "areaName": "Buffer Zone 1"},
    {"cityName": "Karachi", "areaName": "Buffer Zone 2"},
    {"cityName": "Karachi", "areaName": "Burns Road"},
    {"cityName": "Karachi", "areaName": "Cantt"},
    {"cityName": "Karachi", "areaName": "Jacob Lines"},
    {"cityName": "Karachi", "areaName": "Chishti Nagar"},
    {"cityName": "Karachi", "areaName": "City Court"},
    {"cityName": "Karachi", "areaName": "City Railway Station"},
    {"cityName": "Karachi", "areaName": "Civic Centre"},
    {"cityName": "Karachi", "areaName": "Civil Lines"},
    {"cityName": "Karachi", "areaName": "Clifton"},
    {"cityName": "Karachi", "areaName": "Club Road"},
    {"cityName": "Karachi", "areaName": "Dak Khana"},
    {"cityName": "Karachi", "areaName": "Dastgir Colony"},
    {"cityName": "Karachi", "areaName": "Data Nagar"},
    {"cityName": "Karachi", "areaName": "Daud Colony"},
    {"cityName": "Karachi", "areaName": "Defence Garden"},
    {"cityName": "Karachi", "areaName": "Delhi Colony"},
    {"cityName": "Karachi", "areaName": "Denso Hall"},
    {"cityName": "Karachi", "areaName": "DHA City Karachi"},
    {"cityName": "Karachi", "areaName": "DHA Phase 1"},
    {"cityName": "Karachi", "areaName": "DHA Phase 2"},
    {"cityName": "Karachi", "areaName": "DHA Phase 4"},
    {"cityName": "Karachi", "areaName": "DHA Phase 5"},
    {"cityName": "Karachi", "areaName": "DHA Phase 6"},
    {"cityName": "Karachi", "areaName": "DHA Phase 7"},
    {"cityName": "Karachi", "areaName": "DHA Phase 8"},
    {"cityName": "Karachi", "areaName": "Diamond City"},
    {"cityName": "Karachi", "areaName": "Drigh Colony"},
    {"cityName": "Karachi", "areaName": "Essa Nagri"},
    {"cityName": "Karachi", "areaName": "Faisal Cantonment"},
    {"cityName": "Karachi", "areaName": "Farooq-e-Azam"},
    {"cityName": "Karachi", "areaName": "Federal B Area"},
    {"cityName": "Karachi", "areaName": "Firdos Colony"},
    {"cityName": "Karachi", "areaName": "Frere Town"},
    {"cityName": "Karachi", "areaName": "Garden East"},
    {"cityName": "Karachi", "areaName": "Garden West"},
    {"cityName": "Karachi", "areaName": "Gharibabad"},
    {"cityName": "Karachi", "areaName": "Ghaziabad"},
    {"cityName": "Karachi", "areaName": "Gizri"},
    {"cityName": "Karachi", "areaName": "Godhra"},
    {"cityName": "Karachi", "areaName": "Ghous Nagar"},
    {"cityName": "Karachi", "areaName": "Gujjar Chowk"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 1"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 10"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 11"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 12"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 13"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 14"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 15"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 16"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 17"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 18"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 19"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 2"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 20"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 3"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 4"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 5"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 6"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 7"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 8"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 9"},
    {"cityName": "Karachi", "areaName": "Gulistan-e-Jauhar 21"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Iqbal"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 1"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 10"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 11"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 13"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 2"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 3"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 4"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 5"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 6"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 7"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 8"},
    {"cityName": "Karachi", "areaName": "Gulshan-E-Iqbal 9"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Iqbal 12"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Iqbal 14"},
    {"cityName": "Karachi", "areaName": "Gulbahar"},
    {"cityName": "Karachi", "areaName": "Golimar"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Maymar"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Haseen"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Tauheed"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Habib"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Ghazi"},
    {"cityName": "Karachi", "areaName": "Gulberg Town"},
    {"cityName": "Karachi", "areaName": "Green Town"},
    {"cityName": "Karachi", "areaName": "Haidery"},
    {"cityName": "Karachi", "areaName": "Hanifabad"},
    {"cityName": "Karachi", "areaName": "Hussainabad"},
    {"cityName": "Karachi", "areaName": "I.I. Chundrigar Road"},
    {"cityName": "Karachi", "areaName": "Islam Nagar"},
    {"cityName": "Karachi", "areaName": "Jafar-E-Tayyar"},
    {"cityName": "Karachi", "areaName": "Jamaluddin Afghani Road"},
    {"cityName": "Karachi", "areaName": "Jamshed Road"},
    {"cityName": "Karachi", "areaName": "Jinnah Avenue"},
    {"cityName": "Karachi", "areaName": "Jut Line"},
    {"cityName": "Karachi", "areaName": "Kala Board"},
    {"cityName": "Karachi", "areaName": "Karimabad"},
    {"cityName": "Karachi", "areaName": "Karachi Cantonment"},
    {"cityName": "Karachi", "areaName": "Kashmir Road"},
    {"cityName": "Karachi", "areaName": "Khalid Bin Walid Road"},
    {"cityName": "Karachi", "areaName": "Kharadar"},
    {"cityName": "Karachi", "areaName": "KDA 1"},
    {"cityName": "Karachi", "areaName": "KAEHS"},
    {"cityName": "Karachi", "areaName": "Kokhan Colony"},
    {"cityName": "Karachi", "areaName": "Lalukhet"},
    {"cityName": "Karachi", "areaName": "Liaqatabad"},
    {"cityName": "Karachi", "areaName": "Light House"},
    {"cityName": "Karachi", "areaName": "Lyari"},
    {"cityName": "Karachi", "areaName": "MA Jinnah Road"},
    {"cityName": "Karachi", "areaName": "Machar Colony"},
    {"cityName": "Karachi", "areaName": "Manzoor Colony"},
    {"cityName": "Karachi", "areaName": "Maskan Chowrangi"},
    {"cityName": "Karachi", "areaName": "Mehmoodabad"},
    {"cityName": "Karachi", "areaName": "Metroville"},
    {"cityName": "Karachi", "areaName": "Mithadar"},
    {"cityName": "Karachi", "areaName": "Model Colony"},
    {"cityName": "Karachi", "areaName": "Mominabad"},
    {"cityName": "Karachi", "areaName": "Mujahidabad"},
    {"cityName": "Karachi", "areaName": "Muslimabad"},
    {"cityName": "Karachi", "areaName": "Moinabad"},
    {"cityName": "Karachi", "areaName": "Navy Housing Scheme Karsaz"},
    {"cityName": "Karachi", "areaName": "Navy Housing Scheme Zamzama"},
    {"cityName": "Karachi", "areaName": "Nayabad"},
    {"cityName": "Karachi", "areaName": "Naya Nazimabad"},
    {"cityName": "Karachi", "areaName": "Nazimabad"},
    {"cityName": "Karachi", "areaName": "Napier Quarter"},
    {"cityName": "Karachi", "areaName": "New Karachi"},
    {"cityName": "Karachi", "areaName": "North Karachi"},
    {"cityName": "Karachi", "areaName": "North Karachi Buffer Zone"},
    {"cityName": "Karachi", "areaName": "North Nazimabad"},
    {"cityName": "Karachi", "areaName": "Old Clifton"},
    {"cityName": "Karachi", "areaName": "Old Golimar"},
    {"cityName": "Karachi", "areaName": "Orangi Town"},
    {"cityName": "Karachi", "areaName": "P.I.B. Colony"},
    {"cityName": "Karachi", "areaName": "Pakistan Chowk"},
    {"cityName": "Karachi", "areaName": "Parsi Colony"},
    {"cityName": "Karachi", "areaName": "PECHS"},
    {"cityName": "Karachi", "areaName": "PECHS I"},
    {"cityName": "Karachi", "areaName": "PECHS II"},
    {"cityName": "Karachi", "areaName": "PIDC"},
    {"cityName": "Karachi", "areaName": "Punjab Chowrangi"},
    {"cityName": "Karachi", "areaName": "Qaddafi Colony"},
    {"cityName": "Karachi", "areaName": "Qayyumabad"},
    {"cityName": "Karachi", "areaName": "Qasba Colony"},
    {"cityName": "Karachi", "areaName": "Quaidabad"},
    {"cityName": "Karachi", "areaName": "Rashid Minhas Road"},
    {"cityName": "Karachi", "areaName": "Rafah-e-Aam Society"},
    {"cityName": "Karachi", "areaName": "Rizvia Society"},
    {"cityName": "Karachi", "areaName": "Rasheedabad"},
    {"cityName": "Karachi", "areaName": "Saadi Town"},
    {"cityName": "Karachi", "areaName": "Saddar"},
    {"cityName": "Karachi", "areaName": "Saeedabad"},
    {"cityName": "Karachi", "areaName": "Shadman Town"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Colony"},
    {"cityName": "Karachi", "areaName": "Shah Latif Town"},
    {"cityName": "Karachi", "areaName": "Shaheed-e-Millat"},
    {"cityName": "Karachi", "areaName": "Shahra-e-Faisal"},
    {"cityName": "Karachi", "areaName": "Shahra-e-Qaideen"},
    {"cityName": "Karachi", "areaName": "Sindh Industrial Trading Estate"},
    {"cityName": "Karachi", "areaName": "Sarhad Colony"},
    {"cityName": "Karachi", "areaName": "SMCHS - Sindhi Muslim Society"},
    {"cityName": "Karachi", "areaName": "Soldier Bazar"},
    {"cityName": "Karachi", "areaName": "Stadium Road"},
    {"cityName": "Karachi", "areaName": "SITE Area"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Town"},
    {"cityName": "Karachi", "areaName": "Tariq Road"},
    {"cityName": "Karachi", "areaName": "Techno City"},
    {"cityName": "Karachi", "areaName": "Tipu Sultan Road"},
    {"cityName": "Karachi", "areaName": "University Road"},
    {"cityName": "Karachi", "areaName": "Yaseenabad"},
    {"cityName": "Karachi", "areaName": "Yusuf Goth"},
    {"cityName": "Karachi", "areaName": "Zamzama"},
    {"cityName": "Karachi", "areaName": "Korangi"},
    {"cityName": "Karachi", "areaName": "Landhi"},
    {"cityName": "Karachi", "areaName": "Malir"},
    {"cityName": "Karachi", "areaName": "Saudabad"},
    {"cityName": "Karachi", "areaName": "Other"},
    {"cityName": "Karachi", "areaName": "Bahria Town"},
    {"cityName": "Karachi", "areaName": "Abbas Town"},
    {"cityName": "Karachi", "areaName": "Korangi Industrial Area"},
    {"cityName": "Karachi", "areaName": "Reta Plot"},
    {"cityName": "Karachi", "areaName": "korangi No 1"},
    {"cityName": "Karachi", "areaName": "korangi No 2"},
    {"cityName": "Karachi", "areaName": "korangi No 3"},
    {"cityName": "Karachi", "areaName": "korangi No 4"},
    {"cityName": "Karachi", "areaName": "korangi No 5"},
    {"cityName": "Karachi", "areaName": "korangi No 6"},
    {"cityName": "Karachi", "areaName": "landhi No1"},
    {"cityName": "Karachi", "areaName": "landhi No2"},
    {"cityName": "Karachi", "areaName": "landhi No3"},
    {"cityName": "Karachi", "areaName": "landhi No4"},
    {"cityName": "Karachi", "areaName": "landhi No5"},
    {"cityName": "Karachi", "areaName": "landhi No6"},
    {"cityName": "Karachi", "areaName": "malir halt"},
    {"cityName": "Karachi", "areaName": "Memon Goth"},
    {"cityName": "Karachi", "areaName": "Gulshan-e-Malir"},
    {"cityName": "Karachi", "areaName": "Khokhrapar"},
    {"cityName": "Karachi", "areaName": "nazimabad block 1"},
    {"cityName": "Karachi", "areaName": "nazimabad block 2"},
    {"cityName": "Karachi", "areaName": "nazimabad block 3"},
    {"cityName": "Karachi", "areaName": "nazimabad block 4"},
    {"cityName": "Karachi", "areaName": "nazimabad block 5"},
    {"cityName": "Karachi", "areaName": "naya nazimabad A"},
    {"cityName": "Karachi", "areaName": "naya nazimabad B"},
    {"cityName": "Karachi", "areaName": "naya nazimabad C"},
    {"cityName": "Karachi", "areaName": "naya nazimabad D"},
    {"cityName": "Karachi", "areaName": "naya nazimabad E"},
    {"cityName": "Karachi", "areaName": "New karachi Sector A"},
    {"cityName": "Karachi", "areaName": "New karachi Sector B"},
    {"cityName": "Karachi", "areaName": "New karachi Sector C"},
    {"cityName": "Karachi", "areaName": "New karachi Sector D"},
    {"cityName": "Karachi", "areaName": "New karachi Sector E"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector11"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector11-A"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector11-B"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector11-C"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector 12"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector 13"},
    {"cityName": "Karachi", "areaName": "North Karachi Sector 14"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block A"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block B"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block C"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block D"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block E"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block F"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block G"},
    {"cityName": "Karachi", "areaName": "North Nazimabad Block H"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Block 1"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Block 2"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Block 3"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Block 4"},
    {"cityName": "Karachi", "areaName": "Shah Faisal Block 5"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 1"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 2"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 3"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 4"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 5"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 6"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 7"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 8"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 9"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 10"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 11"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 12"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 13"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 14"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 15"},
    {"cityName": "Karachi", "areaName": "Orangi Town Sector 16"},
    {"cityName": "Karachi", "areaName": "Clifton Block 1"},
    {"cityName": "Karachi", "areaName": "Clifton Block 2"},
    {"cityName": "Karachi", "areaName": "Clifton Block 3"},
    {"cityName": "Karachi", "areaName": "Clifton Block 4"},
    {"cityName": "Karachi", "areaName": "Clifton Block 5"},
    {"cityName": "Karachi", "areaName": "Clifton Block 6"},
    {"cityName": "Karachi", "areaName": "Clifton Block 7"},
    {"cityName": "Karachi", "areaName": "Clifton Block 8"},
    {"cityName": "Karachi", "areaName": "Clifton Block 9"}
]

const Area = ({ cityName, value, onChange, disabled }) => {
  const filteredAreas = areaData
    .filter((area) => area.cityName === cityName)
    .map((area) => area.areaName);

  return (
    <div className="tf-select">
      <select
        name="Area"
        id="Area"
        value={value}
        onChange={onChange}
        disabled={disabled || !cityName || filteredAreas.length === 0}
        required
        className="def"
      >
        <option value="" disabled>
          Select Area
        </option>
        {filteredAreas.map((area) => (
          <option key={area} value={area}>
            {area}
          </option>
        ))}
      </select>
    </div>
  );
};

export default Area;